# This file was generated by GoReleaser. DO NOT EDIT.
cask "monmux" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "1518d40ec979e0605f3934d3f336d8aa47477515d7dd6ec361f3313e6680972d"
      url "https://github.com/leinardi/monmux/releases/download/v#{version}/monmux_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "monmux"
  desc "Switch supported monitors between video inputs"
  homepage "https://github.com/leinardi/monmux"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "m1ddc",
    ]

  binary "monmux"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monmux"]
    end
  end

  # No zap stanza required
end
