# This file was generated by GoReleaser. DO NOT EDIT.
cask "monmux" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "1f506f6c60864da30d9e028881a133cb4bb14c571ab242cfeaf0f79232d26e8f"
      url "https://github.com/leinardi/monmux/releases/download/v#{version}/monmux_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "monmux"
  desc "Switch supported monitors between video inputs"
  homepage "https://github.com/leinardi/monmux"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "m1ddc",
    ]

  binary "monmux"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monmux"]
    end
  end

  # No zap stanza required
end
