# This file was generated by GoReleaser. DO NOT EDIT.
cask "monmux" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:         ["-dr", "com.apple.quarantine", "{{staged_path}}/monmux"],
          must_succeed: false
    end
  end

  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "78c15e396a66a3b54143993c250f775a89c62ba943189db19154911b8738f1e1"
      url "https://github.com/leinardi/monmux/releases/download/v#{version}/monmux_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "monmux"
  desc "Switch supported monitors between video inputs"
  homepage "https://github.com/leinardi/monmux"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "m1ddc",
    ]

  binary "monmux"

  # No zap stanza required
end
